name: Package Integration Tests

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-tests:
    uses: dbt-labs/dbt-package-testing/.github/workflows/run_tox.yml@v1
    secrets:
      BIGQUERY_KEYFILE_JSON: ${{ secrets.BIGQUERY_KEYFILE_JSON }}
      DBT_ENV_SECRET_DATABRICKS_TOKEN: "${{ secrets.DBT_ENV_SECRET_DATABRICKS_TOKEN }}"
      DBT_ENV_SECRET_TRINO_PASS: dbt
    with:
      BIGQUERY_PROJECT: dbt-date
      BIGQUERY_SCHEMA: "integration_tests_bigquery_${{ github.run_number }}"
      DATABRICKS_HOST: "${{ vars.DATABRICKS_HOST }}"
      DATABRICKS_HTTP_PATH: "${{ vars.DATABRICKS_HTTP_PATH }}"
      DATABRICKS_SCHEMA: "integration_tests_databricks_${{ github.run_number }}"
      DBT_ENV_SECRET_POSTGRES_PASS: dbt
      POSTGRES_DATABASE: metastore
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA: dbt_date
      POSTGRES_USER: dbt
      TRINO_CATALOG: dbt
      TRINO_HOST: localhost
      TRINO_METHOD: none
      TRINO_PORT: 8080
      TRINO_SCHEMA: "integration_tests_trino_${{ github.run_number }}"
      TRINO_TIMEZONE: UTC
      TRINO_USER: dbt
