repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.2
    hooks:
      - id: sqlfluff-lint
        additional_dependencies: ['dbt-snowflake', 'sqlfluff-templater-dbt']
      - id: sqlfluff-fix
        additional_dependencies: ['dbt-snowflake', 'sqlfluff-templater-dbt']
        
  - repo: https://github.com/offbi/pre-commit-dbt
    rev: v1.0.0
    hooks:
    - id: dbt-docs-generate
    - id: check-model-has-properties-file
      name: Check that all models are listed in a YAML file
      files: ^models/
    - id: check-model-has-tests
      name: Check that all models have tests
      files: ^models/
    - id: check-script-ref-and-source
      nams: Check that all models are using dbt reference functions
      files: ^models/