name: "dbt_date_integration_tests"
version: "1.0"

profile: "integration_tests"

config-version: 2

require-dbt-version: ">=1.10.5"

model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
clean-targets: ["target", "dbt_modules", "dbt_packages"]

flags:
  send_anonymous_usage_stats: false
  use_colors: true
  require_generic_test_arguments_property: true

dispatch:
  - macro_namespace: dbt_date
    search_order: ["dbt_date_integration_tests", "dbt_date"] # enable override

vars:
  dbt_date_dispatch_list: ["dbt_date_integration_tests"]
  "dbt_date:time_zone": "America/Los_Angeles"

models:
  dbt_date_integration_tests:
    +materialized: "{{ 'ephemeral' if target.name == 'trino' else 'table' }}"
