services:
  dbt-postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - DBT_ENV_SECRET_POSTGRES_PASS=dbt
      - POSTGRES_DB=metastore
      - POSTGRES_PASSWORD=dbt
      - POSTGRES_PORT=5432
      - POSTGRES_SCHEMA=dbt_date
      - POSTGRES_USER=dbt

  dbt-spark:
    image: godatadriven/spark:latest
    ports:
      - "10000:10000"
    command: >
      --class org.apache.spark.sql.hive.thriftserver.HiveThriftServer2
      --name Thrift JDBC/ODBC Server

  dbt-trino:
    image: trinodb/trino:latest
    ports:
      - "8080:8080"
